# 액션URL과 상응하는 클래스 맵핑정의.
# ActionName=ClassName
# 기본 메소드명 Init
# http://127.0.0.1:8080/FirstTest.do 라고 호출할 경우 study.FirstAction.processInit 실행.
# ex) 
# call url => http://127.0.0.1:8080/FirstTest.do?action=CodeList
# mapping => FirstTest=study.FirstAction

#시스템.인사정보관리
/ProgramManage=admin.ProgramManageAction
/RoleSetup=admin.RoleSetupAction
/ProgramRoleManage=admin.ProgramRoleManageAction
/UserManage=admin.UserManageAction

#  로그인, 시스템 기초정보, 공통모듈.
/Login=com.LoginAction
/Popup=com.PopupAction
/Menu=com.MenuAction
/CodeManage=com.CodeManageAction
/CompanyManage=com.CompanyManageAction

# 시스템운영.사용자 정의 메시지 관리.
/Message=com.MessageAction
/HelpManage=com.HelpManageAction
/TalkConfig=com.TalkConfigAction
/TemplateConfig=com.TemplateConfigAction

